app:
  name: role-service
  env: dev
  version: v1.0.0

logger:
  level: info
  format: console
  file_path: ./logs/role.log
  zone: alian/Shanghai
database:
  enable: true
  primary:
    driver: postgres
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: 123456
    db_name: role_db
    max_idle: 10
    max_open: 100
    max_lifetime: 3600

redis:
  enable: false

web:
  enable: true
  port: 1110
  mode: debug
  context_path: /api/v1

grpc:
  enable: true
  port: 2110
  reflection: true

consul:
  enable: true
  address: "127.0.0.1:8500"
  tags: ["role", "dev"]
  check:
    interval: "10s"
    timeout: "5s"
    deregister: "30s"

sentinel:
  enable: false